version: "3.9"

volumes:
  data:

services:
  mongodb:
    container_name: products_listing_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
  products_listing_app:
    build: .
    container_name: products_listing_app
    depends_on:
      - mongodb
    ports:
      - "8081:8080"
    environment:
      - spring.data.mongodb.host = mongodb